### ISSUE TITLE
Add auth for all HTTP APIs using shared secret Bearer token

### ISSUE THREAD

**Issue by alexellis** [alexellis/minio-db#4]
## Task

Add auth for all HTTP APIs using shared secret Bearer token

```
./minio-kv --token=$TOKEN

curl localhost:8081/get-blob/my-file.json -H "Authorization: Bearer $TOKEN"
```

^ I'd expect something like the following.

If `--token` is empty or not given, then disable auth

**Comment by zilehuda** [comment]
@alexellis working on it, what do you mean by disable the auth if ```--token``` is not given or empty? do you mean by then the user won't allow to access the resources?

**Comment by utsavanand2** [comment]
PR: [#5](https://github.com/alexellis/minio-kv/pull/5)
